### PR TITLE
changes to run.sh now produce redis-save-rdb.sh, redis-restore-{rdb a…

### PR DESCRIPTION
**Pull request by damora**
…nd aof}.sh, and redis-deleteall.sh

### CODE REVIEW

**Review by cmisale — CHANGES_REQUESTED** [review]
Can we remove the two absolute paths?

**Comment by damora** [comment]
ok, pushed a change with absolute paths removed

**Review by cmisale — APPROVED** [review]

**Review by lasch — COMMENTED** [review]
Any reason why you removed the license header?

**Comment by damora** [comment]
shoot, I accidentally whacked license header and did not realize it. I'll be making another update today with the changes we discussed last night so I'll put it back

**Pull request merged**
