### PR TITLE
fixed group/grouplist names and parameters

### PR DESCRIPTION
**Pull request by cmisale**
Added the empty group define in the python binding.
Update of the examples in binding/python/test to match the empty group name.

### CODE REVIEW

**Review by lasch — COMMENTED** [review]
Any reason why you changed things from varable like libdatabroker.DBR_GROUP_LIST_EMPTY to '0' in dbr.py? Otherwise looks good to me.

**Comment by cmisale** [comment]
Unfortunately I'm forced to, because the typedef for groups is a char*.
I can leave 0 in the #define, but if then I use that value in python (or even just putting an int in the python call), cffi complains because it's expecting a char* and not an integer.
So, we can have 2 solutions:
1. leave that piece of code setting '0' until we don't have any other kind of values and we can write code for cffi accordingly
2. set again dbr.DBR_GROUP_LIST_EMPTY/DBR_GROUP_EMPTY to the value we get from the library (in this case 0), but a. it's not usable in python unless casted to char* or b. the code in tests has to go back to group = '0'.
Since DBR_GROUP_LIST_EMPTY and DBR_GROUP_EMPTY are identifying an empty/null group, I thought that setting '0' (for now or forever) was a not-too-bad alternative to avoid casts and other pain.
 
What do you think?
I'm of course open to changes
_______________________________
Claudia Misale, PhD
Research Staff Member
Cognitive and Cloud, Data-Centric Solutions
IBM T.J. Watson Research Center
Yorktown Heights, NY
 
E-mail: c.misale@ibm.com
Phone: +1 (914) 945-1693  
 
 
----- Original message -----From: Lars Schneidenbach <notifications@github.com>To: IBM/data-broker <data-broker@noreply.github.com>Cc: Claudia Misale <c.misale@ibm.com>, Assign <assign@noreply.github.com>Subject: Re: [IBM/data-broker] fixed group/grouplist names and parameters (#39)Date: Thu, Jan 3, 2019 4:31 PM 
@lasch commented on this pull request.
Any reason why you changed things from varable like libdatabroker.DBR_GROUP_LIST_EMPTY to '0' in dbr.py? Otherwise looks good to me.

**Comment by lasch** [comment]
ok. maybe for now this is the way to go. However, is there an URL-type in python? Because since groups are referring to 'pieces of storage' it could be a good representation to use an URL-like schema to identify/specify storage locations. For example, when thinking of MPI-IO, they are using the type of storage as a prefix and then the path (+file) to make a URL (file://path/filename or gpfs://path/filename). We could go a similar route for the spec of unit locations.

If that exists, what changes would be required in the C definition to accommodate a URL in python?

**Comment by cmisale** [comment]
I investigated a little, looks like with urllib package we will be fine.
It manages web urls, ftp, files.. And looks like strings are fine to define the urls.
Take a look https://docs.python.org/2/library/urllib.html (this is for python 2.7, but for python 3 is the same story)
 
_______________________________
Claudia Misale, PhD
Research Staff Member
Cognitive and Cloud, Data-Centric Solutions
IBM T.J. Watson Research Center
Yorktown Heights, NY
 
E-mail: c.misale@ibm.com
Phone: +1 (914) 945-1693  
 
 
----- Original message -----From: Lars Schneidenbach <notifications@github.com>To: IBM/data-broker <data-broker@noreply.github.com>Cc: Claudia Misale <c.misale@ibm.com>, Assign <assign@noreply.github.com>Subject: Re: [IBM/data-broker] fixed group/grouplist names and parameters (#39)Date: Fri, Jan 4, 2019 9:15 AM 
ok. maybe for now this is the way to go. However, is there an URL-type in python? Because since groups are referring to 'pieces of storage' it could be a good representation to use an URL-like schema to identify/specify storage locations. For example, when thinking of MPI-IO, they are using the type of storage as a prefix and then the path (+file) to make a URL (file://path/filename or gpfs://path/filename). We could go a similar route for the spec of unit locations.
If that exists, what changes would be required in the C definition to accommodate a URL in python?

**Review by lasch — APPROVED** [review]
Reviewed with @cmisale  and decided to leave it as is for now.

**Pull request merged**
