### PR TITLE
better separation of group and group list

### PR DESCRIPTION
**Pull request by lasch**
Cleaner handling and usage of group and group list. While it is still mostly unused and still subject to refinement, this PR is making a better distinction between group and group list arguments. It never caused problems because both types are ptr and were used as NULL.

@cmisale you might have to check how the python components handle this. The 'trick' I was using to find the problems was by changing the type of DBR_Group_t from char* to int. Now the compiler had a chance to complain about incompatible usage. (obviously, this is not part of the committed changes).

### CODE REVIEW

**Review by cmisale — COMMENTED** [review]
I cannot find where DBR_GROUP_EMPTY is declared in the code.. Where is it?

**Comment by lasch** [comment]
I hope it's in `libdatabroker.h`.

**Comment by cmisale** [comment]
I only see DBR_GROUP_LIST_EMPTY.. maybe is not committed? Or I need new glasses

**Comment by lasch** [comment]
No worries, it's well hidden and part of this PR.
here:
https://github.com/IBM/data-broker/pull/37/commits/7cde677f5e1b015b1386f249e5d7afdcc59c4b78#diff-3fab06444ca32725d456829e5d11e59dR253

**Comment by cmisale** [comment]
So I have to change glasses. Anyway, that's almost an alpha renaming process on the API parameters, so it won't be hard for the python counterpart. I have no objections for the PR, I'll fix the python part in the afternoon.

**Review by cmisale — APPROVED** [review]

**Pull request merged**
