### PR TITLE
added stop_allocated function to dbr_utils.py

### PR DESCRIPTION
**Pull request by mdrocco**

### CODE REVIEW

**Review by cmisale — APPROVED** [review]

**Review by lasch — COMMENTED** [review]
Is the use of pdsh causing a new dependency? If yes, I'd suggest to check for the existence/installation of that command before using it. The user might want to know that pdsh is required for this part to work.

**Comment by mdrocco** [comment]
I agree, but unchecked dependencies are already used in the file. At least:

- `pdsh` in stop/save/restore
- `jsrun` in startservers
- `bsub` in start

So I would crate a dedicated issue for the dependency checking.

**Comment by lasch** [comment]
well, jsrun and bsub are somewhat baseline dependencies because this script is about bringup on a LSF/JSM cluster, whereas pdsh might not be a default component of such a cluster.
Anyway, I think it's fine to cover this in a separate issue.

**Review by lasch — APPROVED** [review]

**Comment by mdrocco** [comment]
makes sense, thanks!

**Pull request merged**
