### PR TITLE
Introduced start_allocated function + minor improvements

### PR DESCRIPTION
**Pull request by mdrocco**

### CODE REVIEW

**Review by lasch — COMMENTED** [review]
I like the introduction of the netif parameter. Removes another hardcoded item scattered across the file.
From a quick look it looks good to me. I'll leave the final word to @damora .

**Review by damora — COMMENTED** [review]
Have you tried with daemonize=yes? I had issues with that on the compute nodes before, but maybe that has been fixed.

**Comment by mdrocco** [comment]
It works with my workloads on WSC and Lassen. I would be happy to do more testing if you have something at hand to try.

**Comment by damora** [comment]
> It works with my workloads on WSC and Lassen. I would be happy to do more testing if you have something at hand to try.

Ok, if you've run it then the daemon=yes problem must have been fixed. In the bash script that I originally wrote, I needed daemon=no. I just carried that over to the python script so maybe it was fixed so daemon=yes works now.

**Review by damora — APPROVED** [review]
I like the improvements

**Comment by mdrocco** [comment]
Great, thanks!

**Pull request merged**
